language: generic
dist: "trusty"
sudo: required

cache:
  apt: true

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - g++-5
          sources: *sources

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libboost-dev libboost-system-dev libgtest-dev python3 python3-pip
  - sudo pip3 install 'meson<0.45'
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp

before_script:
  - export PATH=$PWD/.tmp:$PATH

script: ./run-ci-build.sh
