sudo: required
dist: trusty

# specifying cpp here overrides the CXX and CC settings, so we use generic
language: generic

cache:
  apt: true

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-3.8
      - clang-5.0
      - clang-6.0
      - g++-5
      - g++-6
      - g++-7

matrix:
  include:

    ## Debug builds

    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8 CONFIG=Debug

    - os: linux
      env: CXX=clang++-5.0 CC=clang-5.0 CONFIG=Debug

    - os: linux
      env: CXX=clang++-6.0 CC=clang-6.0 CONFIG=Debug

    - os: linux
      env: CXX=g++-5 CC=gcc-5 CONFIG=Debug

    - os: linux
      env: CXX=g++-6 CC=gcc-6 CONFIG=Debug

    - os: linux
      env: CXX=g++-7 CC=gcc-7 CONFIG=Debug


    ## Release builds

    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8 CONFIG=Release

    - os: linux
      env: CXX=clang++-5.0 CC=clang-5.0 CONFIG=Release

    - os: linux
      env: CXX=clang++-6.0 CC=clang-6.0 CONFIG=Release

    - os: linux
      env: CXX=g++-5 CC=gcc-5 CONFIG=Release

    - os: linux
      env: CXX=g++-6 CC=gcc-6 CONFIG=Release

    - os: linux
      env: CXX=g++-7 CC=gcc-7 CONFIG=Release

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libboost-dev libboost-system-dev libgtest-dev cmake cmake-data

script:
  - mkdir -p build
  - cd build
  - cmake -DTVS_ENABLE_TESTS=ON -DTVS_USE_SYSTEMC=OFF -DCMAKE_BUILD_TYPE=$CONFIG ..
  - cmake --build .
  - ctest --verbose .
