language: cpp
dist: "trusty"
sudo: required

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev libboost-system-dev libgtest-dev

install:
  - sudo pip3 install meson
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp

before_script:
  - export PATH=$PWD/.tmp:$PATH

script: ./.run-ci-build.sh