language: cpp
dist: "trusty"
sudo: required

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq g++-6 libboost-dev libboost-system-dev libgtest-dev python3 python3-pip
  - sudo pip3 install meson
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp

before_script:
  - export PATH=$PWD/.tmp:$PATH

script: ./.run-ci-build.sh