sudo: required
dist: trusty
language: cpp

cache:
  apt: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-trusty-5.0
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-3.8
            - gcc-5
      env: CXX=clang++-3.8 CC=clang-3.8

    - os: linux
      addons:
        apt:
          sources: *sources
          packages:
            - clang-5
            - gcc-5
      env: CXX=clang++-5 CC=clang-5

    - os: linux
      addons:
        apt:
          packages:
            - clang-6
            - gcc-5
          sources: *sources
      env: CXX=clang++-6 CC=clang-6

    - os: linux
      addons:
        apt:
          packages:
            - gcc-5
          sources: *sources
      env: CXX=g++-5 CC=gcc-5

    - os: linux
      addons:
        apt:
          packages:
            - gcc-6
          sources: *sources
      env: CXX=g++-6 CC=gcc-6

    - os: linux
      addons:
        apt:
          packages:
            - gcc-7
          sources: *sources
      env: CXX=g++-7 CC=gcc-7

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libboost-dev libboost-system-dev libgtest-dev python3 python3-pip
  - sudo pip3 install 'meson<0.45'
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp

before_script:
  - export PATH=$PWD/.tmp:$PATH
  - env

script: ./run-ci-build.sh
