language: generic
dist: "trusty"
sudo: required

cache:
  apt: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
          packages:
            - clang-3.8
            - g++-5
      env:
        - MATRIX_EVAL="CXX=clang++-3.8 CC=clang-3.8"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5
            - g++-5
      env:
        - MATRIX_EVAL="CXX=clang++-5 CC=clang-5"

    - os: linux
      addons:
        apt:
          packages:
            - clang-6
            - g++-5
          sources:
            - llvm-toolchain-trusty-6.0
      env:
        - MATRIX_EVAL="CXX=clang++-6 CC=clang-6"

    - os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CXX=g++-5 CC=gcc-5"

    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CXX=g++-6 CC=gcc-6"

    - os: linux
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CXX=g++-7 CC=gcc-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libboost-dev libboost-system-dev libgtest-dev python3 python3-pip
  - sudo pip3 install 'meson<0.45'
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp

before_script:
  - export PATH=$PWD/.tmp:$PATH

script: ./run-ci-build.sh
