language: cpp
dist: "trusty"
sudo: required

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev libgtest-dev ninja-build

install:
  - sudo pip3 install meson

script: ./.run-ci-build.sh