sudo: required
dist: trusty

# specifying cpp here overrides the CXX and CC settings, so we use generic
language: generic

cache:
  apt: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-5.0
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-3.8
            - g++-5
      env: CXX=clang++-3.8 CC=clang-3.8

    - os: linux
      addons:
        apt:
          sources: *sources
          packages:
            - clang-5.0
            - g++-5
      env: CXX=clang++-5.0 CC=clang-5.0

    - os: linux
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-5
          sources: *sources
      env: CXX=clang++-6.0 CC=clang-6.0

    - os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
      env: CXX=g++-5 CC=gcc-5

    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources: *sources
      env: CXX=g++-6 CC=gcc-6

    - os: linux
      addons:
        apt:
          packages:
            - g++-7
          sources: *sources
      env: CXX=g++-7 CC=gcc-7

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libboost-dev libboost-system-dev libgtest-dev cmake cmake-data

script:
  - mkdir -p build
  - cd build
  - cmake -DTVS_ENABLE_TESTS=ON -DTVS_USE_SYSTEMC=OFF ..
  - make
  - ctest
